import React from 'react';
import ReactMarkdown from 'react-markdown';
import { FileText, AlertTriangle, CheckCircle, Info } from 'lucide-react';

interface ResultDisplayProps {
  content: string;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ content }) => {
  if (!content) return null;

  return (
    <div className="glass-panel rounded-xl overflow-hidden shadow-2xl border border-glass">
      <div className="bg-glass border-b border-glass p-4 flex items-center justify-between relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-cobalt/10 to-transparent opacity-50"></div>
        <div className="flex items-center gap-3 relative z-10">
          <FileText className="w-5 h-5 text-cobalt" />
          <h2 className="text-sm font-display text-white tracking-widest uppercase">Analysis Report</h2>
        </div>
        <div className="flex gap-2 relative z-10">
          <span className="h-2 w-2 rounded-full bg-cobalt animate-pulse"></span>
          <span className="h-2 w-2 rounded-full bg-tangerine animate-pulse delay-75"></span>
          <span className="h-2 w-2 rounded-full bg-purple-500 animate-pulse delay-150"></span>
        </div>
      </div>
      
      <div className="p-6 md:p-8 font-mono text-sm leading-relaxed text-silver/90">
        <ReactMarkdown
          components={{
            h1: ({node, ...props}) => <h1 className="text-xl font-display text-cobalt mb-6 mt-2 border-b border-cobalt/30 pb-2 uppercase tracking-wider" {...props} />,
            h2: ({node, ...props}) => <h2 className="text-lg font-display text-white mb-4 mt-8 flex items-center gap-2 uppercase tracking-wide" {...props} />,
            h3: ({node, ...props}) => <h3 className="text-base font-display text-tangerine mb-3 mt-6 uppercase tracking-wide" {...props} />,
            ul: ({node, ...props}) => <ul className="space-y-3 mb-6 ml-1" {...props} />,
            li: ({node, ...props}) => (
              <li className="flex items-start gap-3 group" {...props}>
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-cobalt/50 group-hover:bg-cobalt transition-colors flex-shrink-0"></span>
                <span className="group-hover:text-white transition-colors">{props.children}</span>
              </li>
            ),
            strong: ({node, ...props}) => <strong className="text-white font-bold" {...props} />,
            blockquote: ({node, ...props}) => (
              <blockquote className="border-l-2 border-tangerine/50 bg-tangerine/5 pl-4 py-3 my-6 rounded-r-lg italic text-silver/80" {...props} />
            ),
            code: ({node, ...props}) => (
              <code className="bg-obsidian/50 border border-glass px-1.5 py-0.5 rounded text-cobalt text-xs font-mono" {...props} />
            ),
            table: ({node, ...props}) => (
              <div className="overflow-x-auto my-6 rounded-lg border border-glass">
                <table className="w-full text-left border-collapse" {...props} />
              </div>
            ),
            thead: ({node, ...props}) => <thead className="bg-glass text-cobalt uppercase text-xs tracking-wider" {...props} />,
            th: ({node, ...props}) => <th className="p-3 border-b border-glass font-display" {...props} />,
            td: ({node, ...props}) => <td className="p-3 border-b border-glass/50 text-silver/80" {...props} />,
          }}
        >
          {content}
        </ReactMarkdown>
      </div>

      <div className="bg-glass border-t border-glass p-3 text-[10px] font-mono text-muted text-center uppercase tracking-widest">
        End of Report • Generated by Super FC AI • Ref: 9514-SYS
      </div>
    </div>
  );
};

export default ResultDisplay;
